version: '3.8'

services:
  # Service 2: YOLO11 Inference Node
  yolo-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: urllc-yolo-backend
    ports:
      - "8002:80"
    volumes:
      - /dev/shm:/dev/shm
    shm_size: '512mb'
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped